### PR TITLE
Update bip39.go

### PR DESCRIPTION
**Pull request by guotie**
add param raw to control MnemonicToByteArray return raw entropy or checksum entropy

### CODE REVIEW

**Comment by tyler-smith** [comment]
@guotie I am curious as to what the use case is. Do you have a code sample or explanation of what you're doing?

I am not a big fan of abusing variadic parameters in this way, however, if there is a good use case for it seems like the best way to implement the feature now because it can change with the upcoming V2.

**Comment by tyler-smith** [comment]
That's a good point. We should consider for V2 that the analog function to MnemonicToByteArray return the entropy itself and allow the caller to get/apply the checksum if desired.

**Comment by tyler-smith** [comment]
I would much prefer `MnemonicToByteArray` to return without a checksum and to have a separate `MnemonicToByteArrayWithChecksum`, or to have some other API without the variadic parameters.

However, this seems like the best way to implement this feature while remaining backwards compatible.

@guotie Thanks for the change. If what you're doing with bip39 is public I'd love to check it out.

**Comment by guotie** [comment]
Ok.

Thank you.

**Pull request merged**
